travis:
  secure:
    BINSTAR_TOKEN: BUtQ/2R/nEQ7maqfnC6uXJwG+K+a3ur9OSVbO4kHrYgud0jbUJjdeN9ONwUBC+4kmw1acuaGZGP5P00BIoz+294hFqeD3RJoFCR6VYcFSu3YYUKPwouGoWJOD52aWHZFMCOWAVUU175wyrJFVwALxce/8VeLU1vj6UmhkXOzUBebJMcBnEBSSDQxbLBiBpiXd6siqTEK0MGZmCocxjuXdMZi/2ljTUwY9gvGFaWldIjXApdQDi9g29/3zfp6y7lNoAYS953l+zROaWZTdlGEvfD53PBPnmWFmpLdC+Pd6nb76wDf8FhcTlqtWsw/CBGdP5eMezTYPGwCYGtlm/0rhvGwkDe4hN8+/J6NQPZebdFLgObTYhCBadl9OQhV4XlwjDpbZ3FOEfT62Q4IHoOU/WFjP3DFR5L3sEF5br7EywssZmOxppskseYPgC8/i+L3XbM+XuY0ZjQau1BGoD90mHy0+Gk3oXS7FplzcvFHIgkPHI2DMhV29VksaGNB4fcc1sZ3o0p5tXvnDgg6xobfmEWnArc7JpGbgBtLlP6lKAxeeRZZp0MrOQV3+8HHlUZxFO11E8n55olrEBuu5X7/F9jh5kiCUiyuY6ReNE4eyh5ZMZBn5/x1BwrWhXZHHz2vcyeO+MYgx/o8y3JU3s2VzirAR8YiBszpb+8SKr3e+OA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
